[package]
name = "YonkOTP"
version = "0.1.0"
edition = "2024"

[dependencies]
oath = "0.10.2"
rusqlite = "0.28"

[patch.crates-io]
digest = { git = "https://github.com/RustCrypto/hashes.git", tag = "v0.10.3" }
